export default {
  namespaced: true,
  state: {
    provincesText: [
      '台湾',
      '上海',
      '河北',
      '山西',
      '内蒙古',
      '辽宁',
      '吉林',
      '黑龙江',
      '江苏',
      '浙江',
      '安徽',
      '福建',
      '江西',
      '山东',
      '河南',
      '湖北',
      '湖南',
      '广东',
      '广西',
      '海南',
      '四川',
      '贵州',
      '云南',
      '西藏',
      '陕西',
      '甘肃',
      '青海',
      '宁夏',
      '新疆',
      '北京',
      '天津',
      '重庆',
      '香港',
      '澳门'
    ],
    provinces: [
      'taiwan',
      'shanghai',
      'hebei',
      'shanxi',
      'neimenggu',
      'liaoning',
      'jilin',
      'heilongjiang',
      'jiangsu',
      'zhejiang',
      'anhui',
      'fujian',
      'jiangxi',
      'shandong',
      'henan',
      'hubei',
      'hunan',
      'guangdong',
      'guangxi',
      'hainan',
      'sichuan',
      'guizhou',
      'yunnan',
      'xizang',
      'shanxi1',
      'gansu',
      'qinghai',
      'ningxia',
      'xinjiang',
      'beijing',
      'tianjin',
      'chongqing',
      'xianggang',
      'aomen'
    ],
    citysText: [
      '呼伦贝尔市',
      '赤峰市',
      '呼和浩特市',
      '哈尔滨市',
      '大庆市',
      '南宁市',
      '广州市',
      '青岛市',
      '长春市',
      '延边朝鲜族自治州',
      '石家庄市',
      '济南市',
      '郑州市',
      '大连市',
      '沈阳市',
      '锦州市',
      '本溪市',
      '太原市',
      '苏州市',
      '南京市',
      '无锡市'
    ],
    citys: [
      'hulunbeiershi',
      'chifengshi',
      'huhehaoteshi',
      'haerbinshi',
      'daqingshi',
      'nanningshi',
      'guangzhoushi',
      'qingdaoshi',
      'changchunshi',
      'yanbianchaoxianzizhizhou',
      'shijiazhuangshi',
      'jinanshi',
      'zhengzhoushi',
      'dalianshi',
      'shenyangshi',
      'jinzhoushi',
      'benxishi',
      'taiyuanshi',
      'suzhoushi',
      'nanjingshi',
      'wuxishi'
    ],
  },
  mutations: {
    //vuex保存数据
    mapData(state) {
      let data = JSON.parse(window.localStorage.getItem("vuex"))
      state = data.mapData
    }
  },
  actions: {},
  getters: {}
}
