// source: UploadRequest.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.example.proto.CreationRequest', null, global);
goog.exportSymbol('proto.com.example.proto.DeleteRequest', null, global);
goog.exportSymbol('proto.com.example.proto.HeadRequest', null, global);
goog.exportSymbol('proto.com.example.proto.PatchRequest', null, global);
goog.exportSymbol('proto.com.example.proto.UploadRequest', null, global);
goog.exportSymbol('proto.com.example.proto.UploadRequest.Action', null, global);
goog.exportSymbol('proto.com.example.proto.UploadRequest.ImOneofCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.example.proto.UploadRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.example.proto.UploadRequest.oneofGroups_);
};
goog.inherits(proto.com.example.proto.UploadRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.example.proto.UploadRequest.displayName = 'proto.com.example.proto.UploadRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.example.proto.HeadRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.example.proto.HeadRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.example.proto.HeadRequest.displayName = 'proto.com.example.proto.HeadRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.example.proto.PatchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.example.proto.PatchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.example.proto.PatchRequest.displayName = 'proto.com.example.proto.PatchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.example.proto.DeleteRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.example.proto.DeleteRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.example.proto.DeleteRequest.displayName = 'proto.com.example.proto.DeleteRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.example.proto.CreationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.example.proto.CreationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.example.proto.CreationRequest.displayName = 'proto.com.example.proto.CreationRequest';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.example.proto.UploadRequest.oneofGroups_ = [[4,5,6,7]];

/**
 * @enum {number}
 */
proto.com.example.proto.UploadRequest.ImOneofCase = {
  IM_ONEOF_NOT_SET: 0,
  HEADREQUEST: 4,
  PATCHREQUEST: 5,
  DELETEREQUEST: 6,
  CREATIONREQUEST: 7
};

/**
 * @return {proto.com.example.proto.UploadRequest.ImOneofCase}
 */
proto.com.example.proto.UploadRequest.prototype.getImOneofCase = function() {
  return /** @type {proto.com.example.proto.UploadRequest.ImOneofCase} */(jspb.Message.computeOneofCase(this, proto.com.example.proto.UploadRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.example.proto.UploadRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.example.proto.UploadRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.example.proto.UploadRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.UploadRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, 0),
    jwttoken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    filespaceid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    headrequest: (f = msg.getHeadrequest()) && proto.com.example.proto.HeadRequest.toObject(includeInstance, f),
    patchrequest: (f = msg.getPatchrequest()) && proto.com.example.proto.PatchRequest.toObject(includeInstance, f),
    deleterequest: (f = msg.getDeleterequest()) && proto.com.example.proto.DeleteRequest.toObject(includeInstance, f),
    creationrequest: (f = msg.getCreationrequest()) && proto.com.example.proto.CreationRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.example.proto.UploadRequest}
 */
proto.com.example.proto.UploadRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.example.proto.UploadRequest;
  return proto.com.example.proto.UploadRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.example.proto.UploadRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.example.proto.UploadRequest}
 */
proto.com.example.proto.UploadRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.example.proto.UploadRequest.Action} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setJwttoken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilespaceid(value);
      break;
    case 4:
      var value = new proto.com.example.proto.HeadRequest;
      reader.readMessage(value,proto.com.example.proto.HeadRequest.deserializeBinaryFromReader);
      msg.setHeadrequest(value);
      break;
    case 5:
      var value = new proto.com.example.proto.PatchRequest;
      reader.readMessage(value,proto.com.example.proto.PatchRequest.deserializeBinaryFromReader);
      msg.setPatchrequest(value);
      break;
    case 6:
      var value = new proto.com.example.proto.DeleteRequest;
      reader.readMessage(value,proto.com.example.proto.DeleteRequest.deserializeBinaryFromReader);
      msg.setDeleterequest(value);
      break;
    case 7:
      var value = new proto.com.example.proto.CreationRequest;
      reader.readMessage(value,proto.com.example.proto.CreationRequest.deserializeBinaryFromReader);
      msg.setCreationrequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.example.proto.UploadRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.example.proto.UploadRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.example.proto.UploadRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.UploadRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getJwttoken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFilespaceid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHeadrequest();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.example.proto.HeadRequest.serializeBinaryToWriter
    );
  }
  f = message.getPatchrequest();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.example.proto.PatchRequest.serializeBinaryToWriter
    );
  }
  f = message.getDeleterequest();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.com.example.proto.DeleteRequest.serializeBinaryToWriter
    );
  }
  f = message.getCreationrequest();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.com.example.proto.CreationRequest.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.com.example.proto.UploadRequest.Action = {
  HEAD: 0,
  PATCH: 1,
  DELETE: 2,
  CREATION: 3
};

/**
 * optional Action action = 1;
 * @return {!proto.com.example.proto.UploadRequest.Action}
 */
proto.com.example.proto.UploadRequest.prototype.getAction = function() {
  return /** @type {!proto.com.example.proto.UploadRequest.Action} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.com.example.proto.UploadRequest.Action} value
 * @return {!proto.com.example.proto.UploadRequest} returns this
 */
proto.com.example.proto.UploadRequest.prototype.setAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string jwtToken = 2;
 * @return {string}
 */
proto.com.example.proto.UploadRequest.prototype.getJwttoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.UploadRequest} returns this
 */
proto.com.example.proto.UploadRequest.prototype.setJwttoken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string fileSpaceId = 3;
 * @return {string}
 */
proto.com.example.proto.UploadRequest.prototype.getFilespaceid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.UploadRequest} returns this
 */
proto.com.example.proto.UploadRequest.prototype.setFilespaceid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional HeadRequest headRequest = 4;
 * @return {?proto.com.example.proto.HeadRequest}
 */
proto.com.example.proto.UploadRequest.prototype.getHeadrequest = function() {
  return /** @type{?proto.com.example.proto.HeadRequest} */ (
    jspb.Message.getWrapperField(this, proto.com.example.proto.HeadRequest, 4));
};


/**
 * @param {?proto.com.example.proto.HeadRequest|undefined} value
 * @return {!proto.com.example.proto.UploadRequest} returns this
*/
proto.com.example.proto.UploadRequest.prototype.setHeadrequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.com.example.proto.UploadRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.example.proto.UploadRequest} returns this
 */
proto.com.example.proto.UploadRequest.prototype.clearHeadrequest = function() {
  return this.setHeadrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.example.proto.UploadRequest.prototype.hasHeadrequest = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional PatchRequest patchRequest = 5;
 * @return {?proto.com.example.proto.PatchRequest}
 */
proto.com.example.proto.UploadRequest.prototype.getPatchrequest = function() {
  return /** @type{?proto.com.example.proto.PatchRequest} */ (
    jspb.Message.getWrapperField(this, proto.com.example.proto.PatchRequest, 5));
};


/**
 * @param {?proto.com.example.proto.PatchRequest|undefined} value
 * @return {!proto.com.example.proto.UploadRequest} returns this
*/
proto.com.example.proto.UploadRequest.prototype.setPatchrequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.com.example.proto.UploadRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.example.proto.UploadRequest} returns this
 */
proto.com.example.proto.UploadRequest.prototype.clearPatchrequest = function() {
  return this.setPatchrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.example.proto.UploadRequest.prototype.hasPatchrequest = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional DeleteRequest deleteRequest = 6;
 * @return {?proto.com.example.proto.DeleteRequest}
 */
proto.com.example.proto.UploadRequest.prototype.getDeleterequest = function() {
  return /** @type{?proto.com.example.proto.DeleteRequest} */ (
    jspb.Message.getWrapperField(this, proto.com.example.proto.DeleteRequest, 6));
};


/**
 * @param {?proto.com.example.proto.DeleteRequest|undefined} value
 * @return {!proto.com.example.proto.UploadRequest} returns this
*/
proto.com.example.proto.UploadRequest.prototype.setDeleterequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.com.example.proto.UploadRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.example.proto.UploadRequest} returns this
 */
proto.com.example.proto.UploadRequest.prototype.clearDeleterequest = function() {
  return this.setDeleterequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.example.proto.UploadRequest.prototype.hasDeleterequest = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional CreationRequest creationRequest = 7;
 * @return {?proto.com.example.proto.CreationRequest}
 */
proto.com.example.proto.UploadRequest.prototype.getCreationrequest = function() {
  return /** @type{?proto.com.example.proto.CreationRequest} */ (
    jspb.Message.getWrapperField(this, proto.com.example.proto.CreationRequest, 7));
};


/**
 * @param {?proto.com.example.proto.CreationRequest|undefined} value
 * @return {!proto.com.example.proto.UploadRequest} returns this
*/
proto.com.example.proto.UploadRequest.prototype.setCreationrequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.com.example.proto.UploadRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.example.proto.UploadRequest} returns this
 */
proto.com.example.proto.UploadRequest.prototype.clearCreationrequest = function() {
  return this.setCreationrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.example.proto.UploadRequest.prototype.hasCreationrequest = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.example.proto.HeadRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.example.proto.HeadRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.example.proto.HeadRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.HeadRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.example.proto.HeadRequest}
 */
proto.com.example.proto.HeadRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.example.proto.HeadRequest;
  return proto.com.example.proto.HeadRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.example.proto.HeadRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.example.proto.HeadRequest}
 */
proto.com.example.proto.HeadRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.example.proto.HeadRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.example.proto.HeadRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.example.proto.HeadRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.HeadRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string fileId = 1;
 * @return {string}
 */
proto.com.example.proto.HeadRequest.prototype.getFileid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.HeadRequest} returns this
 */
proto.com.example.proto.HeadRequest.prototype.setFileid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.example.proto.PatchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.example.proto.PatchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.example.proto.PatchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.PatchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uploadoffset: jspb.Message.getFieldWithDefault(msg, 3, 0),
    chunksize: jspb.Message.getFieldWithDefault(msg, 4, 0),
    data: msg.getData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.example.proto.PatchRequest}
 */
proto.com.example.proto.PatchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.example.proto.PatchRequest;
  return proto.com.example.proto.PatchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.example.proto.PatchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.example.proto.PatchRequest}
 */
proto.com.example.proto.PatchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUploadoffset(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChunksize(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.example.proto.PatchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.example.proto.PatchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.example.proto.PatchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.PatchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUploadoffset();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getChunksize();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
};


/**
 * optional string fileId = 1;
 * @return {string}
 */
proto.com.example.proto.PatchRequest.prototype.getFileid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.PatchRequest} returns this
 */
proto.com.example.proto.PatchRequest.prototype.setFileid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 uploadOffset = 3;
 * @return {number}
 */
proto.com.example.proto.PatchRequest.prototype.getUploadoffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.example.proto.PatchRequest} returns this
 */
proto.com.example.proto.PatchRequest.prototype.setUploadoffset = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 chunkSize = 4;
 * @return {number}
 */
proto.com.example.proto.PatchRequest.prototype.getChunksize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.example.proto.PatchRequest} returns this
 */
proto.com.example.proto.PatchRequest.prototype.setChunksize = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bytes data = 5;
 * @return {!(string|Uint8Array)}
 */
proto.com.example.proto.PatchRequest.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes data = 5;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.com.example.proto.PatchRequest.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.com.example.proto.PatchRequest.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.com.example.proto.PatchRequest} returns this
 */
proto.com.example.proto.PatchRequest.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.example.proto.DeleteRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.example.proto.DeleteRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.example.proto.DeleteRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.DeleteRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.example.proto.DeleteRequest}
 */
proto.com.example.proto.DeleteRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.example.proto.DeleteRequest;
  return proto.com.example.proto.DeleteRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.example.proto.DeleteRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.example.proto.DeleteRequest}
 */
proto.com.example.proto.DeleteRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.example.proto.DeleteRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.example.proto.DeleteRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.example.proto.DeleteRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.DeleteRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string fileId = 1;
 * @return {string}
 */
proto.com.example.proto.DeleteRequest.prototype.getFileid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.DeleteRequest} returns this
 */
proto.com.example.proto.DeleteRequest.prototype.setFileid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.example.proto.CreationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.example.proto.CreationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.example.proto.CreationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.CreationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    hashsha512: jspb.Message.getFieldWithDefault(msg, 1, ""),
    filename: jspb.Message.getFieldWithDefault(msg, 2, ""),
    filesize: jspb.Message.getFieldWithDefault(msg, 3, 0),
    parentid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    taskid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    projectid: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.example.proto.CreationRequest}
 */
proto.com.example.proto.CreationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.example.proto.CreationRequest;
  return proto.com.example.proto.CreationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.example.proto.CreationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.example.proto.CreationRequest}
 */
proto.com.example.proto.CreationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHashsha512(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFilesize(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setParentid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaskid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.example.proto.CreationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.example.proto.CreationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.example.proto.CreationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.example.proto.CreationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHashsha512();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFilesize();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getParentid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTaskid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getProjectid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string hashSHA512 = 1;
 * @return {string}
 */
proto.com.example.proto.CreationRequest.prototype.getHashsha512 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.CreationRequest} returns this
 */
proto.com.example.proto.CreationRequest.prototype.setHashsha512 = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string fileName = 2;
 * @return {string}
 */
proto.com.example.proto.CreationRequest.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.CreationRequest} returns this
 */
proto.com.example.proto.CreationRequest.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 fileSize = 3;
 * @return {number}
 */
proto.com.example.proto.CreationRequest.prototype.getFilesize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.example.proto.CreationRequest} returns this
 */
proto.com.example.proto.CreationRequest.prototype.setFilesize = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string parentId = 4;
 * @return {string}
 */
proto.com.example.proto.CreationRequest.prototype.getParentid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.CreationRequest} returns this
 */
proto.com.example.proto.CreationRequest.prototype.setParentid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string taskId = 5;
 * @return {string}
 */
proto.com.example.proto.CreationRequest.prototype.getTaskid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.CreationRequest} returns this
 */
proto.com.example.proto.CreationRequest.prototype.setTaskid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string projectId = 6;
 * @return {string}
 */
proto.com.example.proto.CreationRequest.prototype.getProjectid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.example.proto.CreationRequest} returns this
 */
proto.com.example.proto.CreationRequest.prototype.setProjectid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.com.example.proto);
